import type { Wake } from '@/lib/push';
import { DEFAULT_SEND_HOUR, wakeTimes } from '@/lib/push';

/**
 * What is uploaded, and when.
 *
 * This file is the whole privacy surface. Every byte that leaves the device on
 * account of reminders is assembled here, in one function, so the claim on the
 * settings card can be checked by reading forty lines rather than a codebase.
 *
 * If anything is ever added to `SyncPayload` that names a thing you own, the
 * design has quietly become an ordinary cloud reminder service. test/push.test.ts
 * asserts against that directly.
 */

/**
 * Everything the sender is told.
 *
 *   endpoint   where to deliver. Generated by the browser, on Google's or
 *              Apple's infrastructure — the sender did not choose it and
 *              cannot use it for anything except delivering a push.
 *   keys       the browser's own encryption keys. Web Push requires them even
 *              for an empty body; they let the browser verify the message came
 *              from the holder of our VAPID key and nobody else.
 *   wakes      epoch seconds. When to ping. Nothing about why.
 *
 * No name, no title, no kind, no count of what sort of thing is due. The words
 * are written on the device and read from the device — see lib/push.ts.
 */
export interface SyncPayload {
  endpoint: string;
  keys: { p256dh: string; auth: string };
  wakes: number[];
}

/**
 * A cap, and the reason is not storage.
 *
 * A long list of instants is a fingerprint. Sixty days of a busy household is
 * a handful of dates; anything approaching a hundred is either a bug or an
 * attempt to encode something in the shape of the list. Truncating to the
 * nearest ones is also the right behaviour on its own terms — a reminder eight
 * weeks out is not urgent, and the schedule is resynced long before then.
 */
export const MAX_WAKES = 40;

export function syncPayload(
  sub: PushSubscriptionJSON,
  schedule: Wake[],
  hour = DEFAULT_SEND_HOUR,
): SyncPayload | null {
  const endpoint = sub.endpoint;
  const p256dh = sub.keys?.p256dh;
  const auth = sub.keys?.auth;
  if (!endpoint || !p256dh || !auth) return null;

  return { endpoint, keys: { p256dh, auth }, wakes: wakeTimes(schedule, hour).slice(0, MAX_WAKES) };
}

/**
 * Weekly, not on every change.
 *
 * The obvious thing is to resync whenever the schedule changes, and it is the
 * wrong thing: a sender that hears from you the moment you add a subscription
 * can watch you use the app. Times of day, frequency, the pattern of an
 * evening spent entering receipts — none of that is in the payload, and all of
 * it is in the timing of the requests.
 *
 * A weekly batch flattens that to "this device checked in". The cost is that a
 * newly added document might not be known to the sender for a few days, which
 * matters only for something that needs starting inside a week — and that one
 * is already sitting on the dashboard.
 */
export const SYNC_EVERY_DAYS = 7;

export function syncDue(lastAt: string | undefined, now = new Date()): boolean {
  if (!lastAt) return true;
  const then = Date.parse(lastAt);
  if (Number.isNaN(then)) return true;
  return now.getTime() - then >= SYNC_EVERY_DAYS * 86_400_000;
}

/**
 * Whether a schedule differs in the way the sender would care about.
 *
 * Compared on the uploaded shape rather than on the app's own records: editing
 * an item's name changes the notification text and changes nothing the sender
 * holds, so it is not a reason to talk to it.
 */
export function wakesChanged(a: number[], b: number[]): boolean {
  return a.length !== b.length || a.some((t, i) => t !== b[i]);
}
